version: "3.9"

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "9411:9411"
      - "16686:16686"
      - "14268:14268"
    networks:
      - trancing
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
  api:
    image: cosmtrek/air
    working_dir: /project
    volumes:
      - ./api:/project/
    ports:
      - "3001:8081"
    environment:
      - PORT=8081
      - JEAGER_ENDPOINT=http://jaeger:14268/api/traces
      - SERVICE_NAME=go-api
      - ENVIROMENT=develop
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
      - ME_CONFIG_MONGODB_URL=mongodb://root:example@mongo:27017/
    depends_on:
      - jaeger
    networks:
      - trancing
networks:
  trancing:
    driver: bridge
